# Generated by Django 4.1 on 2022-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('profile_name', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('BANNED', 'BANNED'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=255)),
                ('profile_updated', models.BooleanField(blank=True, default=False, null=True)),
                ('total_commented', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
