# Generated by Django 4.1 on 2022-08-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='email',
        ),
    ]
