# Generated by Django 4.1 on 2022-08-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_user_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
